"use client";
import { App, Button, Card, Descriptions, Form, Input, Modal, Select, Space, Tag } from "antd";
import { ArrowLeftOutlined } from "@ant-design/icons";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams, useRouter } from "next/navigation";
import { useState } from "react";
import { financeApi } from "../../../../src/features/finance/api";
import { FinanceApprovalTimeline } from "../../../../src/features/finance/components/finance-approval-timeline";
import { FinanceAttachmentUpload } from "../../../../src/features/finance/components/finance-attachment-upload";
import { getFinanceApprovalStatusLabel, getFinanceStatusTone, formatCentsAsYuan } from "../../../../src/features/finance/display";
import { useAuthStore } from "../../../../src/stores/auth-store";

export default function ExpenseDetailPage() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const storeId = useAuthStore((s) => s.user?.storeMember?.store.id); const client = useQueryClient(); const { message } = App.useApp(); const [reviewOpen, setReviewOpen] = useState(false); const [form] = Form.useForm(); const query = useQuery({ queryKey: ["finance-expense", id], queryFn: () => financeApi.expense(id), enabled: Boolean(id) }); const review = useMutation({ mutationFn: (v: { decision: "APPROVE" | "REJECT"; note?: string }) => financeApi.reviewExpense(id, v), onSuccess: () => { message.success("审批结果已保存"); setReviewOpen(false); void client.invalidateQueries({ queryKey: ["finance-expense", id] }); } }); const item = query.data; return <div className="management-page"><Space><Button icon={<ArrowLeftOutlined />} onClick={() => router.push("/finance/expenses")}>返回费用申请</Button><h1>费用申请详情</h1></Space>{item ? <><Card title={item.applicationNo ?? item.id} extra={<Tag color={getFinanceStatusTone(item.status)}>{getFinanceApprovalStatusLabel(item.status)}</Tag>}><Descriptions column={2}><Descriptions.Item label="费用标题">{item.title}</Descriptions.Item><Descriptions.Item label="金额">{formatCentsAsYuan(item.amountCents)}</Descriptions.Item><Descriptions.Item label="用途说明" span={2}>{item.reason}</Descriptions.Item></Descriptions></Card><Card title="附件"><FinanceAttachmentUpload applicationType="expenses" applicationId={id} initialAttachments={item.attachments} /></Card><Card title="审批记录"><FinanceApprovalTimeline records={item.approvalRecords} /></Card>{item.allowedActions?.includes("REVIEW_EXPENSE") ? <Button type="primary" onClick={() => setReviewOpen(true)}>处理审批</Button> : null}<Modal title="审批费用申请" open={reviewOpen} onCancel={() => setReviewOpen(false)} okText="保存" onOk={() => form.submit()}><Form form={form} layout="vertical" onFinish={(v) => review.mutate(v)}><Form.Item name="decision" label="审批结果" rules={[{ required: true }]}><Select options={[{ value: "APPROVE", label: "通过" }, { value: "REJECT", label: "驳回" }]} /></Form.Item><Form.Item name="note" label="审批意见"><Input.TextArea rows={4} /></Form.Item></Form></Modal></> : null}</div>; }
