import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const pagePath = join(process.cwd(), "app", "settings", "page.tsx");
const page = () => readFileSync(pagePath, "utf8") + readFileSync(join(process.cwd(), "app", "settings", "workbench-client.tsx"), "utf8");
test("system settings is a capability-driven responsibility workbench", () => { const source = page(); assert.match(source, /settingsApi\.capabilities/); assert.match(source, /groupCapabilities/); assert.match(source, /我的职责/); assert.match(source, /查看全部设置/); });
test("workbench exposes all four responsibility domains and server statuses", () => { const source = page(); assert.match(source, /DOMAIN_ICONS/); assert.match(source, /CapabilityCard/); assert.match(source, /capabilityStatus/); assert.match(source, /规划中/); });
test("workbench does not render unimplemented actions as enabled controls", () => { const source = page(); assert.match(source, /disabled=\{!canOpen\}/); assert.match(source, /!capability\.planned/); });
test("workbench includes forbidden and implemented settings routes", () => { const source = page(); assert.match(source, /settings\/dictionaries/); assert.match(source, /settings\/audit/); assert.match(source, /settings\/all/); });
test("settings styles include responsive responsibility cards", () => { const css = readFileSync(join(process.cwd(), "app", "globals.css"), "utf8"); assert.match(css, /settings-workbench-header/); assert.match(css, /settings-capability-grid/); assert.match(css, /@media \(max-width: 900px\)/); });
test("settings entry supports legacy read-only rollback mode", () => { const source = readFileSync(pagePath, "utf8") + readFileSync(join(process.cwd(), "app", "settings", "legacy", "page.tsx"), "utf8"); assert.match(source, /NEXT_PUBLIC_SETTINGS_WORKBENCH_MODE/); assert.match(source, /兼容只读模式/); });