"use client";
import { Suspense, useCallback, useEffect, useState } from "react";
import { Alert, Button, Card, Empty, List, Space, Spin, Tag, Typography, App } from "antd";
import { ArrowLeftOutlined, DownloadOutlined } from "@ant-design/icons";
import { useRouter, useSearchParams } from "next/navigation";
import { settingsApi, type MigrationReview, type SettingsAuditRow } from "../../../src/features/settings/api";
import { SettingsCapabilityGuard } from "../../../src/features/settings/capability-guard";
export default function SettingsAuditPage() { return <SettingsCapabilityGuard capabilityCodes={["settings.audit.global", "finance.audit"]}><Suspense fallback={<div className="management-page"><Spin tip="正在加载审计…" /></div>}><SettingsAuditContent /></Suspense></SettingsCapabilityGuard>; }
function SettingsAuditContent() { const router=useRouter(); const search=useSearchParams(); const {message}=App.useApp(); const [rows,setRows]=useState<SettingsAuditRow[]>([]); const [total,setTotal]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null); const [reviews,setReviews]=useState<MigrationReview[]>([]); const domain=search.get("domain") ?? ""; const load=useCallback(async()=>{setLoading(true); try { const result=await settingsApi.audit(domain ? `domain=${encodeURIComponent(domain)}` : ""); setRows(result.rows); setTotal(result.total); setError(null); } catch(reason){setError(reason instanceof Error?reason.message:"审计加载失败");} finally{setLoading(false);}},[domain]); useEffect(()=>{void load();},[load]); useEffect(()=>{settingsApi.migrationReviews().then(setReviews).catch(()=>setReviews([]));},[]); const resolveReview=async(review:MigrationReview,status:"RESOLVED"|"IGNORED")=>{const reason=window.prompt(status==="RESOLVED"?"请输入确认说明":"请输入忽略原因");if(!reason?.trim())return;try{await settingsApi.resolveMigrationReview(review.id,status,reason.trim());setReviews((current)=>current.filter((item)=>item.id!==review.id));message.success(status==="RESOLVED"?"迁移项已确认":"迁移项已忽略");}catch(reason){message.error(reason instanceof Error?reason.message:"迁移项处理失败");}}; const exportAudit=async()=>{try{const result=await settingsApi.exportAudit(domain?`domain=${encodeURIComponent(domain)}`:""); const csv=["操作,对象类型,对象ID,操作人,门店,时间,元数据",...result.rows.map((row)=>[row.action,row.targetType,row.targetId??"",row.actorId??"系统",row.storeId??"",new Date(row.createdAt).toISOString(),JSON.stringify(row.metadata)].map((value)=>`"${String(value).replace(/"/g, '""')}"`).join(","))].join("\\n"); const blob=new Blob(["\\uFEFF"+csv],{type:"text/csv;charset=utf-8"}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download="settings-audit.csv"; link.click(); URL.revokeObjectURL(url); message.success(`已导出 ${result.rows.length} 条审计记录`);}catch(reason){message.error(reason instanceof Error?reason.message:"导出失败");}}; return <div className="management-page settings-workspace"><Space direction="vertical" size={20} style={{width:"100%"}}><Space><Button icon={<ArrowLeftOutlined/>} onClick={()=>router.push("/settings")}>返回职责工作台</Button><Button icon={<DownloadOutlined/>} onClick={()=>void exportAudit()}>安全导出</Button></Space><div><Typography.Title level={2}>设置审计</Typography.Title><Typography.Paragraph type="secondary">服务端按角色和当前门店范围过滤；敏感字段已脱敏，超过 10,000 条的导出会被拒绝。</Typography.Paragraph></div>
<Card title={`迁移待确认（${reviews.length}）`} size="small">{reviews.length===0?<Typography.Text type="secondary">暂无待人工确认项</Typography.Text>:<List dataSource={reviews} renderItem={(review)=><List.Item actions={[<Button key="resolve" type="link" onClick={()=>void resolveReview(review,"RESOLVED")}>确认</Button>,<Button key="ignore" type="link" danger onClick={()=>void resolveReview(review,"IGNORED")}>忽略</Button>]}><List.Item.Meta title={`${review.sourceType} · ${review.sourceId}`} description={review.reason}/></List.Item>}/>}</Card>{loading?<Spin tip="正在加载审计记录…"/>:error?<Alert type="error" showIcon message={error} action={<Button onClick={()=>void load()}>重新加载</Button>}/>:rows.length===0?<Empty description="当前暂无审计记录"/>:<CardList rows={rows} total={total}/>}</Space></div>; }
function CardList({rows,total}:{rows:SettingsAuditRow[];total:number}){return <List header={<Typography.Text type="secondary">共 {total} 条记录</Typography.Text>} dataSource={rows} renderItem={(row)=><List.Item><List.Item.Meta title={<Space><Tag color="blue">{row.action}</Tag><span>{row.targetType}</span></Space>} description={<Space direction="vertical" size={2}><span>对象：{row.targetId ?? "-"} · 操作人：{row.actorId ?? "系统"}</span><span>{new Date(row.createdAt).toLocaleString()}</span></Space>}/></List.Item>}/>;}